/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(AWGN_bez_FEC.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(900b3691f8a17093176263c98c9c2044)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ErTools/AWGN_bez_FEC.h>
// pydoc.h is automatically generated in the build directory
#include <AWGN_bez_FEC_pydoc.h>

void bind_AWGN_bez_FEC(py::module& m)
{

    using AWGN_bez_FEC    = gr::ErTools::AWGN_bez_FEC;


    py::class_<AWGN_bez_FEC, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<AWGN_bez_FEC>>(m, "AWGN_bez_FEC", D(AWGN_bez_FEC))

        .def(py::init(&AWGN_bez_FEC::make),
           D(AWGN_bez_FEC,make)
        )
        



        ;




}








