/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(AWGN_kanal.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4873226dd24307d29df5640d0d092215)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ErTools/AWGN_kanal.h>
// pydoc.h is automatically generated in the build directory
#include <AWGN_kanal_pydoc.h>

void bind_AWGN_kanal(py::module& m)
{

    using AWGN_kanal = ::gr::ErTools::AWGN_kanal;


    py::class_<AWGN_kanal,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<AWGN_kanal>>(m, "AWGN_kanal", D(AWGN_kanal))

        .def(py::init(&AWGN_kanal::make),
             py::arg("N"),
             py::arg("EbN0min"),
             py::arg("EbN0max"),
             D(AWGN_kanal, make))


        ;
}
