/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(BER_moje.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ff250cb4c3374daca5d6346eef0b255a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ErTools/BER_moje.h>
// pydoc.h is automatically generated in the build directory
#include <BER_moje_pydoc.h>

void bind_BER_moje(py::module& m)
{

    using BER_moje = ::gr::ErTools::BER_moje;


    py::class_<BER_moje,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<BER_moje>>(m, "BER_moje", D(BER_moje))

        .def(py::init(&BER_moje::make),
             py::arg("N"),
             py::arg("Rb"),
             py::arg("EbN0min"),
             py::arg("EbN0max"),
             D(BER_moje, make))


        ;
}
