/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(BER_Curve_Sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3e946297bd434ac9c6fdfce230a7a17a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ErTools/BER_Curve_Sink.h>
// pydoc.h is automatically generated in the build directory
#include <BER_Curve_Sink_pydoc.h>

void bind_BER_Curve_Sink(py::module& m)
{

    using BER_Curve_Sink    = gr::ErTools::BER_Curve_Sink;


    py::class_<BER_Curve_Sink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<BER_Curve_Sink>>(m, "BER_Curve_Sink", D(BER_Curve_Sink))

        .def(py::init(&BER_Curve_Sink::make),
           D(BER_Curve_Sink,make)
        )
        



        ;




}








