/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(BitErrorRate.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(82e293fe6b427095ae7876356a94dd22)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ErTools/BitErrorRate.h>
// pydoc.h is automatically generated in the build directory
#include <BitErrorRate_pydoc.h>

void bind_BitErrorRate(py::module& m)
{

    using BitErrorRate    = gr::ErTools::BitErrorRate;


    py::class_<BitErrorRate, gr::block, gr::basic_block,
        std::shared_ptr<BitErrorRate>>(m, "BitErrorRate", D(BitErrorRate))

        .def(py::init(&BitErrorRate::make),
           D(BitErrorRate,make)
        )
        



        ;




}








