/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(MC.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(397e5deeb5513eb7d8d870178633f38d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ErTools/MC.h>
// pydoc.h is automatically generated in the build directory
#include <MC_pydoc.h>

void bind_MC(py::module& m)
{

    using MC    = gr::ErTools::MC;


    py::class_<MC, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<MC>>(m, "MC", D(MC))

        .def(py::init(&MC::make),
           D(MC,make)
        )
        



        ;




}








