/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(SER.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(94d0a3ab5e797d59b14c346a1e120978)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ErTools/SER.h>
// pydoc.h is automatically generated in the build directory
#include <SER_pydoc.h>

void bind_SER(py::module& m)
{

    using SER    = gr::ErTools::SER;


    py::class_<SER, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<SER>>(m, "SER", D(SER))

        .def(py::init(&SER::make),
           D(SER,make)
        )
        



        ;




}








