/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ctest.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(13612f8fbde79700aea51c4f0be07c67)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/tempPY/ctest.h>
// pydoc.h is automatically generated in the build directory
#include <ctest_pydoc.h>

void bind_ctest(py::module& m)
{

    using ctest    = gr::tempPY::ctest;


    py::class_<ctest, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<ctest>>(m, "ctest", D(ctest))

        .def(py::init(&ctest::make),
           D(ctest,make)
        )
        



        ;




}








