/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(Dekoder_Opak.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9133edb8cf37fedfdcc96cc6e42e023b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/KodKal/Dekoder_Opak.h>
// pydoc.h is automatically generated in the build directory
#include <Dekoder_Opak_pydoc.h>

void bind_Dekoder_Opak(py::module& m)
{

    using Dekoder_Opak    = gr::KodKal::Dekoder_Opak;


    py::class_<Dekoder_Opak, gr::sync_decimator,
        std::shared_ptr<Dekoder_Opak>>(m, "Dekoder_Opak", D(Dekoder_Opak))

        .def(py::init(&Dekoder_Opak::make),
           D(Dekoder_Opak,make)
        )
        



        ;




}








